### ISSUE TITLE
Lots of legit mails blocked on SpamAssassin KAM_BODY_URIBL_PCCC

### ISSUE THREAD

**Issue by gvansanden** [E-F-A/v3#135]
Hi, Since last week I started seeing lots of mails being blocked with a spamassassin analysis like this:
-1.90	BAYES_00	 
0.00	FREEMAIL_FROM	 
1.00	FREEMAIL_REPLY	 
0.00	HTML_MESSAGE	 
2.04	HTML_TITLE_SUBJ_DIFF	 
5.00	KAM_BODY_URIBL_PCCC	 
-0.00	RCVD_IN_DNSWL_NONE	 
-0.00	SPF_PASS	 
0.00	URIBL_BLOCKED	 

The culprit is the KAM_BODY_URIBL_PCCC, I cannot find out why it triggers.  I updated KAM.cf to downgrade the score as a fix, but it gets overwritten every day.

On request, I can send you an example mail gzipped by mail (not in a public ticket of course).

**Comment by shawniverson** [comment]
This rule is firing on the red list...that shouldn't be happening....
Should fire only on black and grey

**Comment by shawniverson** [comment]
Updated KAM.cf appears to resolve

Force updates at end of EFA-Init

**Comment by shawniverson** [comment]
Added in commit a636ba18553205920d4ebfd905c9cd7f871a1dfd
