### ISSUE TITLE
GeoIP database hosting

### ISSUE THREAD

**Issue by darky83** [E-F-A/v3#140]
it seems the mailwatch file download for geoip is broken

The file is downloaded to /var/www/html/mailscanner/temp/
then the file is imported into the sql database.

however the downloaded file contains the following text:

his website is using a security service to protect itself from online attacks. The action you just performed triggered the security solution. There are several actions that could trigger this block including submitting a certain word or phrase, a SQL command or malformed dat

**Comment by shawniverson** [comment]
Original issue was temporary.  Pushing back to next major update.

**Comment by shawniverson** [comment]
Check terms of Maxmind GeoIP Lite redistribution

**Comment by shawniverson** [comment]
Geolite and Geolite2 are redistributable under the Creative Commons Attribution-ShareAlike 4.0 International License.  We will proceed as planned.

**Comment by shawniverson** [comment]
Pushing back to speed up 3.0.1.2 release
