### ISSUE TITLE
minor feature request: sort the list of domains at Mail Settings / Transport settings

### ISSUE THREAD

**Issue by pdwalker** [E-F-A/v3#158]
in /var/EFA/lib/EFA-Configure/func_mailsettings:48 (v3.0.0.7)

change 
```bash
RELAYS=( `cat /etc/postfix/transport | grep smtp: | sed '/^\#/d;/^$/d;s/smtp:\[//;s/\]//'` )
```
to
```bash
RELAYS=( `cat /etc/postfix/transport | grep smtp: | sort | sed '/^\#/d;/^$/d;s/smtp:\[//;s/\]//'` )
```

warning:
I didn't test anything else other than the display, so my suggested change might break other things in a horrible fashion, or there might be a better way to implement this

**Comment by shawniverson** [comment]
Added in commit 77bb0523559f14dabdd10b14c35bec55949c1ee2
