### ISSUE TITLE
Get webinterface to work with https by default

### ISSUE THREAD

**Issue by darky83** [E-F-A/v3#179]
Default https with self signed certificate,
provide an easy way to add 'real' certificates.

provide an easy way to switch back to http only

**Comment by ressel87** [comment]
Maybe it could be useful to use https://letsencrypt.org/ when it's out of beta?

**Comment by shawniverson** [comment]
Sounds good to me :+1:

**Comment by shawniverson** [comment]
Added https by default in commit fa8bd998946454873c38f69bc86d6f32b5a3b576

Leaving issue open to add letencrypt.org support

**Comment by shawniverson** [comment]
lets encrypt a separate issue, closing
