### ISSUE TITLE
Wildcard support in whitelist/blacklist

### ISSUE THREAD

**Issue by evharten** [E-F-A/v3#180]
Eg, using *@*.domainname.extention , or *@domainname.ext

Currently we have to use the full names, and spammers often use generated email addresses ;)

**Comment by shawniverson** [comment]
http://docs.mailwatch.org/using/faq.html

**Comment by shawniverson** [comment]
Tip:  You can do this instead.  Simply leave the username portion blank

From: @domain.com
To: default
