### ISSUE TITLE
EFA-Configure v2.0

### ISSUE THREAD

**Issue by shawniverson** [E-F-A/v3#181]
Instead of a separate configurator for each setting...

Create a definition for each setting.  File/db, pattern, validation rule, description, default, category, type etc.

Code EFA-Configure to pull definitions in and construct menu and choices.

May allow for more rapid and easier add of settings to EFA-Configure.

**Comment by darky83** [comment]
I'd like to make the second version web-based actually.
Already working on an mockup

**Comment by shawniverson** [comment]
I was thinking of doing both...web based and CLI using the same schema.  That way if something prevents accessing the web GUI you can go in and still configure.

**Comment by shawniverson** [comment]
Bumping back to 3.1.0.0 for now to expedite 3.0.0.9 release
