### ISSUE TITLE
EFA Service Monitoring

### ISSUE THREAD

**Issue by shawniverson** [E-F-A/v3#187]
Create monitor for services on EFA.

1) Attempt to restart services (3x max)
2) Alert on service failure if possible
3) Log on service failure if possible
4) Create a maintenance mode in EFA-Configure to allow for servicing

**Comment by darky83** [comment]
Also: graphs

Want to use munin to get some detailed system stats
Nice to see and also usefull for triubleshoorting performance issued..

For monitoring we could write it our self or use xymon or nagios.

**Comment by shawniverson** [comment]
Added in commit a37afb6a05b2b5f7ce79c78b6546cb2431fedddf
