### ISSUE TITLE
quarantine_report.php issues

### ISSUE THREAD

**Issue by shawniverson** [E-F-A/v3#199]
1) formatting issues in text and html formatting
2) multiple to's not supported
3) action not populated or displayed

**Comment by shawniverson** [comment]
update mailwatch to resolve issue in next update

**Comment by darky83** [comment]
Also add php-mbstring:
sudo yum install php-mbstring
sudo service httpd restart"

https://forum.efa-project.org/viewtopic.php?f=14&t=1196

**Comment by shawniverson** [comment]
Mailwatch updated in commit 9e32db41a893a05cb6a7b2c296c917236bf692d2
