### ISSUE TITLE
UTF8 Characters Not Rendering in MailWatch

### ISSUE THREAD

**Issue by shawniverson** [E-F-A/v3#204]
https://forum.efa-project.org/viewtopic.php?f=5&t=1186&p=4089#p4089

**Comment by shawniverson** [comment]
Fixed (mostly) in commit 9e32db41a893a05cb6a7b2c296c917236bf692d2

Other UTF8 issues are being addressed by the MailWatch team.

**Comment by mcLays** [comment]
After upgrade to EFA 3.0.1.2 and mailwatch 1.2.0 RC2 UTF8 characters not displaying properly again.
Should we modify MailWatch.pm line 294
from:
$msg{subject} = fix_latin($message->{subject});
to:
$msg{subject} = fix_latin($message->{utf8subject});

**Comment by shawniverson** [comment]
Thanks for suggestion!  I will test and submit to MailWatch project.

**Comment by shawniverson** [comment]
Fixed in MailWatch develop branch.
