### ISSUE TITLE
Postfix Postscreen Support

### ISSUE THREAD

**Issue by shawniverson** [E-F-A/v3#205]
Add support for postscreen to EFA.  It may be mutually exclusive to greylisting, so it may require greylisting off before enabling.

**Comment by shawniverson** [comment]
Bumping priority, try to get into next update

**Comment by shawniverson** [comment]
postfix upgraded, testing postscreen

**Comment by shawniverson** [comment]
bumping back by popular vote

**Comment by ovizii** [comment]
Hey Shawn, how is this progressing? Its much awaited ;-)

**Comment by shawniverson** [comment]
Slow progress...really busy at the moment.

**Comment by ovizii** [comment]
Thanks for the update, much appreciated.

**Comment by shawniverson** [comment]
Moved to v4

https://github.com/E-F-A/v4/issues/9
