### ISSUE TITLE
Postfix reject_unverified_recipient

### ISSUE THREAD

**Issue by shawniverson** [E-F-A/v3#218]
Add this as an enable/disable option to EFA-Configure

https://forum.efa-project.org/viewtopic.php?f=14&t=1266&p=4570

**Comment by jakubeliasz** [comment]
how to do this manually?

I tried adding "reject_unverified_recipient" right after "reject_unknown_recipient_domain" but postfix complains on invalid configuration.

Should it replace "check_recipient_access hash:/etc/postfix/recipient_access" (empty, tried adding "domain.tld reject_unknown_recipient" line there, seems that's not the way)
