### ISSUE TITLE
Automated non-interactive EFA-Init

### ISSUE THREAD

**Issue by shawniverson** [E-F-A/v3#226]
https://forum.efa-project.org/viewtopic.php?f=14&t=1358&p=4920

**Comment by thctlo** [comment]
You can try and/or improve this installer script. 
https://github.com/thctlo/clamav-unofficial-sigs 
its a fork off the official clamav-unofficial-sigs with only and installer added. 
I think you can use if you modify the installer a bit.

**Comment by shawniverson** [comment]
Deferring for now, limited impact on audience
