### ISSUE TITLE
build script not building spamassassin

### ISSUE THREAD

**Issue by mcLays** [E-F-A/v3#230]
cd /usr/src/EFA
    wget $mirror/$mirrorpath/Spamassassin-3.4.0a-EFA-Upgrade.tar.gz
    tar -xvzf Spamassassin-3.4.0a-EFA-Upgrade.tar.gz
    cd Spamassassin*

have to change to:

    cd /usr/src/EFA
    wget $mirror/$mirrorpath/Spamassassin-3.4.0a-EFA-Upgrade.tar.gz
    tar -xvzf Spamassassin-3.4.0a-EFA-Upgrade.tar.gz
    cd Spamassassin-3.4.0-*

**Comment by shawniverson** [comment]
Fixed in commit 1333e188910b34f423ed71c13c2bde867f69534f
