### ISSUE TITLE
Possible name collision in MailWatch queries

### ISSUE THREAD

**Issue by shawniverson** [E-F-A/v3#234]
https://forum.efa-project.org/viewtopic.php?f=14&t=1393&p=5070

**Comment by herromega** [comment]
Problem is in Mailwatch file functions.php at line 2538 and 2540.
change 

if ((defined('FILTER_TO_ONLY') && FILTER_TO_ONLY)) {
    $sqladdr_arr[] = "to_address like '%$address%'";
} else {
    $sqladdr_arr[] = "to_address like '%$address%' OR from_address = '$address'";
}

to this

if ((defined('FILTER_TO_ONLY') && FILTER_TO_ONLY)) {
    $sqladdr_arr[] = "to_address like '$address%'";
} else {
    $sqladdr_arr[] = "to_address like '$address%' OR from_address = '$address'";
}

**Comment by shawniverson** [comment]
Filing with MailWatch

**Comment by shawniverson** [comment]
Fixed in commit b1a85dd5d1237c06f9b129b58aa13289eccd55a2
