### ISSUE TITLE
Postfix catchall address support

### ISSUE THREAD

**Issue by shawniverson** [E-F-A/v3#250]

**Comment by shawniverson** [comment]
https://forum.efa-project.org/viewtopic.php?f=15&t=1416&p=5318

**Comment by shawniverson** [comment]
no catchalls

**Comment by 9swampy** [comment]
> no catchalls

Just to be clear the redirect to postfix worked:

> sudo nano /etc/postfix/virtual

Add whatever @domain.com	user@domain.com you need. uder@domain.com you created already in Efa's User Management

> sudo postmap /etc/postfix/virtual
sudo postfix reload

Job done.
