### ISSUE TITLE
EFA 3.0.0.8 kept mailing recipients of a flagged SPAM mail that came in

### ISSUE THREAD

**Issue by gvansanden** [E-F-A/v3#267]
I ran into a very strange problem with EFA 3.0.0.8. There was a legitimate mail sent to a big list of recipients, one of which was behind my EFA server.

EFA identified the mail as spam (though legitimate, it did have many SPAM like characteristics) and placed it in quarantine. So far so good.

Instead of mailing the recipient locally only, EFA mailed ALL recipients in the TO field the quarantine message dozens to a hundred times...

I have no idea why this happened, it has never happened before or on any other message. I would like to find out what went wrong and how I can make sure it doesn't happen again.

Posted it on the forum and another user had the same issue.
https://forum.efa-project.org/viewtopic.php?f=13&t=1561&p=5770#p5770

**Comment by shawniverson** [comment]
Trying to determine cause of issue, suspect mailscanner, release-msg.cgi, or both.

**Comment by shawniverson** [comment]
Was the message a {spam not delivered} message?  Did it have a release link in the sig line?  Do you have your mailscanner config you could share (minus watermark secret)?

**Comment by shawniverson** [comment]
See also https://github.com/E-F-A/v3/issues/201

**Comment by shawniverson** [comment]
Going to focus on upgrading MailScanner and phasing out release-msg.cgi in hopes this is a bug on the version in use in EFA

**Comment by shawniverson** [comment]
release-msg.cgi deprecated in commit 275cbf42e12bff27ca28f43170b302b5f3d54fcf

**Comment by shawniverson** [comment]
Waiting on MailScanner v5 release

**Comment by shawniverson** [comment]
MailScanner upgraded in commit 3da9fbffef43a8d36a7e3a611a93e0e2403d9047
