### ISSUE TITLE
Special symbols in passwords failing with LDAP

### ISSUE THREAD

**Issue by shawniverson** [E-F-A/v3#298]
https://forum.efa-project.org/viewtopic.php?f=13&t=1754

**Comment by shawniverson** [comment]
Bumping back, really a MailWatch issue

**Comment by danbrunt** [comment]
What does this mean then?

**Comment by danbrunt** [comment]
and submitted the bug to mailwatch... 
[https://github.com/mailwatch/1.2.0/issues/309]

**Comment by shawniverson** [comment]
Fixed in MailWatch develop branch
