### ISSUE TITLE
Release of password protected archives

### ISSUE THREAD

**Issue by sriccio** [E-F-A/v3#343]
Hi,

Actually when a user receives a mail with a password protected attachment it's being blocked as a potentially dangerous message.
This is great to avoid viruses nested inside password protected archives.

BUT

Sometimes a user receives a legit password protected archive and would like to have it delivered in his mailbox.
So I activated the quarantaining of "silent viruses" and this provide the user with a release link for that particular e-mail.

But then when you want release it, it is requeued from "postmaster" (whitelisted) so it can be delivered.
This works for spam messages but not for dangerous content like password protected archives.

I guess because the whitelisting doesn't bypass the dangerous content check, only the spam checks.

So it get quarantined again... and there is no way to deliver the message to the inbox.

So the question is, is it possible to have MailScanner bypass all checks (including dangerous content) when the sender is whitelisted ? 

That would be very nice to have maybe a configurable option (depending on sysadmin wishes) to tell MailScanner to do the whitelisting check before anything else.

It would resolve the issue for releasing password protected archives and some others I guess!

Thanks for reading,
Sébastien

**Comment by shawniverson** [comment]
Can you confirm the settings as described in the MailWatch faq here?

http://docs.mailwatch.org/using/faq.html

**Comment by sriccio** [comment]
Hi thanks for your answer.
I've reviewed the files, the only file differing is:

/etc/MailScanner/rules/spam.whitelist.rules (original file from EFA hyper-v image)
```
# If you are basing a blacklist on this then you can refer to
# a null (empty) sender address with "/^$/" as the address to match.
#
# This is where you can build a Spam WhiteList
# Addresses matching in here, with the value
# "yes" will never be marked as spam.
#From:          152.78.         yes
#From:          130.246.        yes
#From:          host:soton.ac.uk yes # Note this is slower than using the IP
FromOrTo:       default         no
```
I've changed it to the example in the FAQ, but it had no impact.

My current content scanning setup is:
```
%rules-dir% = /etc/MailScanner/rules
Dangerous Content Scanning = %rules-dir%/content.scanning.rules
```

cat /etc/MailScanner/rules/content.scanning.rules 
```
From:   127.0.0.1       no
FromOrTo:       default yes
```

Seems to be good, but I still can't release the file. It repops in the messages list, marked as W/L OTHER but from 127.0.0.1 and postmaster.

**Comment by sriccio** [comment]
For additional informations, here is the log output of MailScanner when releasing the message from 

> MailWatch interface:
> Dec 27 23:31:49 mx1 postfix/pickup[64743]: 0B0B2340119: uid=48 from=<postmaster@swisscenter.com>
> Dec 27 23:31:49 mx1 postfix/cleanup[3635]: 0B0B2340119: hold: header Received: by mx1.swisscenter.com (Postfix, from userid 48)??id 0B0B2340119; Tue, 27 Dec 2016 23:31:48 +0100 (CET) from local; from=<postmaster@swisscenter.com> to=<madjik@syndroma.ch>
> Dec 27 23:31:49 mx1 postfix/cleanup[3635]: 0B0B2340119: message-id=<45d76eb85cb54f7b8ed98cd9a8bcfc18@ex1.obs.local>
> Dec 27 23:31:50 mx1 MailScanner[53909]: New Batch: Scanning 1 messages, 5992 bytes
> Dec 27 23:31:50 mx1 MailScanner[53909]: Password-protected archive (tracks.zip) in 0B0B2340119.AA3FE
> Dec 27 23:31:50 mx1 MailScanner[53909]: Virus and Content Scanning: Starting
> Dec 27 23:31:50 mx1 MailScanner[53909]: Viruses marked as silent: MailScanner: Message contained password-protected archive
> Dec 27 23:31:50 mx1 MailScanner[53909]: Saved entire message to /var/spool/MailScanner/quarantine/20161227/0B0B2340119.AA3FE
> Dec 27 23:31:50 mx1 MailScanner[53909]: Saved infected "tracks.zip" to /var/spool/MailScanner/quarantine/20161227/0B0B2340119.AA3FE
> Dec 27 23:31:50 mx1 MailScanner[53909]: Spam Checks: Starting
> Dec 27 23:31:50 mx1 MailScanner[53909]: Expired 3 records from the SpamAssassin cache
> Dec 27 23:31:50 mx1 MailScanner[53909]: Whitelist refresh time reached
> Dec 27 23:31:50 mx1 MailScanner[53909]: Starting up SQL Whitelist
> Dec 27 23:31:50 mx1 MailScanner[53909]: Read 2 whitelist entries
> Dec 27 23:31:50 mx1 MailScanner[53909]: Message 0B0B2340119.AA3FE from 127.0.0.1 (postmaster@swisscenter.com) is whitelisted
> Dec 27 23:31:56 mx1 MailScanner[53909]: Deleted 1 messages from processing-database
> Dec 27 23:31:56 mx1 MailScanner[53909]: Logging message 0B0B2340119.AA3FE to SQL

**Comment by shawniverson** [comment]
Try this:

/etc/MailScanner/MailScanner.conf
```
# Should archives which contain any password-protected files be allowed?
# Leaving this set to "no" is a good way of protecting against all the
# protected zip files used by viruses at the moment.
# This can also be the filename of a ruleset.
Allow Password-Protected Archives = %rules-dir%/password-archive.rules
```

Create /etc/MailScanner/rules/password-archive.rules  (tab spacing)
```
From:     127.0.0.1           yes
FromOrTo:  default          no
```

**Comment by sriccio** [comment]
Tested and approved !

It's now possible to release password protected archives.

Thanks a lot for your help.

Now at least the user can request a release of these kind of e-mails.

Still, what do you think about the possibility to allow whitelist to skip these checks like it skips spam checks ? 

You know how some people are : "If I whitelist someone, I want to be able to receive anything from them even if it's a virus..."

Thanks again for your amazing help.
