### ISSUE TITLE
EFA 3.0.1.6 mailwatch is empty after Update GeoIP Database

### ISSUE THREAD

**Issue by str1k3r** [E-F-A/v3#346]
https://forum.efa-project.org/viewtopic.php?f=13&t=863 - same issue, but it valid for the latest update...

**Comment by radiogena** [comment]
same issue. After update to EFA-3.0.1.6 I've made Geo IP update from the web interface and mailwatch messages shows only the following.  
Received on:	12/01/17 17:22:03
Received by:	domain.name
Received from: ip address

if I've delete /var/www/html/mailscanner/temp and delete geoip.* everything is showing but geo names now.

**Comment by shawniverson** [comment]
https://forum.efa-project.org/viewtopic.php?f=13&t=2113&p=7964

**Comment by shawniverson** [comment]
Confirmed.

**Comment by shawniverson** [comment]
Testing MailWatch RC4 Code for issue

**Comment by shawniverson** [comment]
Fixed in commit f0d46257d2f1ce87a953bf017828c51acd314303 

Publishing 3.0.1.7 update

**Comment by shawniverson** [comment]
Testing latest development branch of MailWatch

**Comment by shawniverson** [comment]
Bug present in latest development branch, engaging MailWatch development

**Comment by shawniverson** [comment]
Fixed in commit 61043a4f5cc5ff4ef456b79eba95881eebfd9393

Performing further tests for 3.0.1.7
