### ISSUE TITLE
Obvious spams getting through because of RP_MATCHES_RCVD

### ISSUE THREAD

**Issue by gvansanden** [E-F-A/v3#348]
I started getting massive amounts of the same spams selling contact databases.
They all pass EFA (3.0.1.5/3.0.1.8) because the negative score of a valid return path.

For example:
0.80 BAYES_50
1.10 DCC_CHECK
0.29 DIGEST_MULTIPLE
0.00 HEADER_FROM_DIFFERENT_DOMAINS
0.00 HTML_MESSAGE
0.43 MIME_HTML_MOSTLY
0.79 MPART_ALT_DIFF
1.39 PYZOR_CHECK
-3.20 RP_MATCHES_RCVD
-0.00 SPF_PASS
0.00 URIBL_BLOCKED

I know I can modify that myself, but it will keep on getting overwritten. Is this a new and general tactic spammers are using?

**Comment by shawniverson** [comment]
RP_MATCHES_RCVD means that the email received matches the correct return path.  Of course spammers are going to try to look legit.  You can override this score permanently in /etc/mail/spamassassin/local.cf by placing a different score there instead.

**Comment by gvansanden** [comment]
Ok, thanks!
