### ISSUE TITLE
Default postfix message_size_limit

### ISSUE THREAD

**Issue by sriccio** [E-F-A/v3#349]
Hi,

When installing EFA (at least from the iso) there is no `message_size_limit` defined in postfix configuration.

The built-in value of postfix is then very low and doesn't allow a lot of messages with attachment to be accepted.

Maybe a `message_size_limit` with some reasonable value should be added in postfix configuration.
Around 40-50MB maybe ?

Just a suggestion :)

Best regards,
Sébastien

**Comment by shawniverson** [comment]
Moving to v4

https://github.com/E-F-A/v4/issues/4
