### ISSUE TITLE
Edit transport destinations

### ISSUE THREAD

**Issue by shawniverson** [E-F-A/v3#364]
https://forum.efa-project.org/viewtopic.php?f=15&p=9011

**Comment by DavidRawling** [comment]
Yeah I have to upvote this one. Mid mail migration - I have just a dozen domains to reconfigure, I can't imagine how annoying it would be to have many more - since each one requires a delete/add cycle, or two edits.

**Comment by shawniverson** [comment]
Added in commit 2a81240326dd7c27bef8f2ffc7786c1ba6638934
