### ISSUE TITLE
mod_security disable id 981320

### ISSUE THREAD

**Issue by shawniverson** [E-F-A/v3#367]
https://forum.efa-project.org/viewtopic.php?f=13&t=2348

**Comment by johnjore** [comment]
Similar problem. Upgraded to 3.0.2.2. Problem still there when blacklisting the domain `@distinctivesearch.top`

Error in /var/log/httpd/ssl_error_log:

> [Fri May 05 10:37:36 2017] [error] [client x.x.x.x] ModSecurity: Access denied with code 403 (phase 2). Operator GE matched 3 at TX:sqli_select_statement_count. [file "/etc/httpd/modsecurity.d/activated_rules/modsecurity_crs_41_sql_injection_attacks.conf"] [line "108"] [id "981317"] [rev "2"] [msg "SQL SELECT Statement Anomaly Detection Alert"] [data "Matched Data: Cookie found within TX:sqli_select_statement_count: 3"] [ver "OWASP_CRS/2.2.6"] [maturity "8"] [accuracy "8"] [tag "OWASP_CRS/WEB_ATTACK/SQL_INJECTION"] [tag "WASCTC/WASC-19"] [tag "OWASP_TOP_10/A1"] [tag "OWASP_AppSensor/CIE1"] [tag "PCI/6.5.2"] [hostname "xxx"] [uri "/mailscanner/lists.php"] [unique_id "WQxH4MCoAQwAAAgQawgAAAAD"]

Note that the line number above will be different as I initially tried to comment out two other lines as outlined in the link above with a comment. 

After this change, problem has gone away. Note that my EFA server is not directly exposed to the internet, a store and forward box is in front. The weakening of the security on this box is therefore not as much a concern for me as it can be for others.

JJ

**Comment by shawniverson** [comment]
That's a good compromise, how about we add a feature to disable mod_security to EFA-Configure?  That way admins have a choice as to whether they want to use it or not.

**Comment by johnjore** [comment]
That would work for me.

**Comment by shawniverson** [comment]
Added configurable option in commit 1df3ce6c2fd95883496cb403e1c0307770090727

**Comment by shawniverson** [comment]
Added exceptions in commit e509b2111674dad6b00d9683b5e885548d9ba969
