### ISSUE TITLE
UTF8 Rendering on PHP 5.3 Issue

### ISSUE THREAD

**Issue by shawniverson** [E-F-A/v3#368]
https://forum.efa-project.org/viewtopic.php?f=13&t=2319&start=25

**Comment by pdwalker** [comment]
please note my "fix" for 5.3 was hardcoded and may not necessarily the best way to handle the fix.  Better explanation and fix here: https://github.com/mailwatch/MailWatch/issues/773

**Comment by shawniverson** [comment]
PHP upgrade is not viable option on CentOS 6x.  This is a reason for me to keep with development of v4.

Going to mark Wontfix.  This will be resolved with CentOS 7.
