### ISSUE TITLE
message list empty after fresh install CentOS 6.9 + 3.0.2.3 kickstart

### ISSUE THREAD

**Issue by jakubeliasz** [E-F-A/v3#371]
I have used the latest kickstart file, however just now on the wiki regarding building eFa I see that I should use http://dl.efa-project.org/build/3/ks.cfg, which points at release 3.0.1.9

Is building with CentOS 6.9 + release 3.0.1.9 and upgrading to latest afterwards the way to go?

**Comment by shawniverson** [comment]
Try this

http://dl.efa-project.org/build/3.0.2.3/ks.cfg

I'll go in and update the link on the server so that it points to 3.0.2.3.

**Comment by jakubeliasz** [comment]
yes, I used the 3.0.2.3 kickstart with CentOS 6.9 and got this issue with messages not showing up on the list/quarantine while I could see them in the logs and also daily message count...

Installing now with /3/ks.cfg

**Comment by jakubeliasz** [comment]
getting even more strange now :) after fresh install with C6.9 + 3.0.1.9 I now get "The requested URL /mailscanner/ was not found on this server."

No issues however with the production filter installed a while ago with C6.8 ISO and 3.0.1.4 kickstart, and later gradually updated to latest 3.0.2.3

**Comment by jakubeliasz** [comment]
fresh build with CentOS 6.9 + 3.0.2.2 kickstart seems OK, at least the "recent messages"/quarantine items seem to show up. I'll do yet another build with C6.9 + 3.0.2.3 ks to make sure I can reproduce the earlier issue and post the log if that's the case

**Comment by jakubeliasz** [comment]
all seems to be fine this time..
