### ISSUE TITLE
MailWatch-AD-Sync

### ISSUE THREAD

**Issue by TheGr8Wonder** [E-F-A/v3#377]
The script works great, and the TODO look great as well..

Some thoughts for those that use an Exchange environment...

I ran this script, and it imported my users without issue. It however also imported all of my HealthMalboxes, Migration mailboxes, and other system related mailboxes. Perhaps some user filtering to exclude these system mailboxes - I can dig up an example for the filter.

Also if admins of the EFA enable per user scoring, it'll work great for the users that were freshly imported. However if there are distribution lists (public groups) then any spam sent to these addresses will not get scored, and pose as "my spam filter isn't working" by end users who are part of said groups. 

I'm not sure of the best way to handle this case, but it would also fall under "shared" mailboxes as well within Exchange.

**Comment by TheGr8Wonder** [comment]
This script will also import any external contacts you have specified within Exchange as well, as users within EFA.

**Comment by shawniverson** [comment]
Not the least surprised.  The script uses the LDAP_FILTER defined in conf.php, which looks like this:

define('LDAP_FILTER', 'mail=%s'); 

So anything with an email address is getting pulled in.  What we need is a locally defined filter in the script that can be modified to filter more aggressively as needed.  Unfortunately, the 'LDAP_FILTER' in conf.php is a LDAP notation field and not the entire LDAP notation string with parenthesis.

For per_user filtering....we need to include distribution lists so that spam scoring holds.  Again, the locally defined filter will be fine.  We can then include or exclude groups in the filter definition and drop the hard coded group exclusion.

**Comment by TheGr8Wonder** [comment]
The filter will only import groups, if the group was configured as a security group. Distribution groups and dynamic distribution groups within exchange are not imported via this script, which is why my groups did not carry over, and will cause the issue as described above. 

Also the per-user spam checking can not be changed by end-user for imported security groups, only administrator or domain admin must do this. 

This has been confirmed in 3 separate installs of exchange and EFA now. Exchange 2016 and EFA 3.0.2.3 in both, but i suspect since the AD objects are treated the same, you will see this regardless of the exchange version. 

That is true with both when mail or proxyaddresses are defined within conf.php, and both fields are defined on the distribution group object within AD.

**Comment by shawniverson** [comment]
Understood.  It should be possible to include them, I believe.  I don't have a local Exchange instance, though, do the DLs and dynamic DLs exist in AD, or just Exchange?

**Comment by TheGr8Wonder** [comment]
They exists within AD as groups, under the OU you specify during creation of the group, and have the proper AD attributes (both mail and ProxyAddresses) set on each object

**Comment by shawniverson** [comment]
Cool, so I can create them w/o Exchange and test against them....

**Comment by schrotn** [comment]
The way to differentiate between distribution and security groups is the groupType ldap attribute.  Distribution is 0x2 and security is 0x80000002.
Also, according to a technet article, these are the filters you can apply to get one specific or multiple types of ldap entries:

objectCategory | objectClass | Result
-- | -- | --
person | user | user objects
person |   | user and contact objects
person | contact | contact objects
  | user | user and computer objects
computer |   | computer objects
user |   | user and contact objects
  | contact | contact objects
  | computer | computer objects
  | person | user, computer, and contact objects
contact |   | user and contact objects
group |   | group objects
  | group | group objects
person | organizationalPerson | user and contact objects
  | organizationalPerson | user, computer, and contact objects
organizationalPerson |   | user and contact objects

Sorry if you've already seen this.  I'm evaluating EFA for use at my office, and would like the ability to import my groups as aliases into EFA and figured I'd try to help.  
Personally, I'd like to only import distribution groups as I make that distinction when setting up a dist vs security group.  But I'm sure the options can be easily set any way the user wants.

**Comment by schrotn** [comment]
Fair warning: I'm far from a PHP programmer.  I know enough to hack at it.  Feel free to tidy it up to your standards if you want to use it.
This should separate out the actual users and groups from the rest of the LDAP entries it receives:

    $ldap_search_results = 
        ldap_search($ds, LDAP_DN, "(&(" . LDAP_USERNAME_FIELD . "=" . $character . "*)(" . sprintf(LDAP_FILTER, '*') . "))",
            array(LDAP_USERNAME_FIELD,'objectclass','objectcategory','groupType','displayName','mail','proxyaddresses'),0,0) 
            or die(__('ldpaauth203'));
    
    if ($DEBUG === true && ( $ldap_search_results === false || ldap_count_entries($ds, $ldap_search_results) === 0 )) {
        echo("No entries for" . $character . '\n');
    }

    // Prepare to iterate and sync
    if ($ldap_search_results !== false && ldap_count_entries($ds, $ldap_search_results) >= 1) {
        $results = ldap_get_entries($ds, $ldap_search_results) or die(__('ldpaauth303'));
        ldap_free_result($ldap_search_results);
        foreach ($results as $result) {
            if (is_array($result['objectclass']) === true && is_array($result['objectcategory']) === true) {
                if (in_array('user', array_values($result['objectclass']), true) === true && in_array('person', array_values($result['objectcategory']),true) === true) {
                    **User code removed for length**
                } 
                elseif (in_array('group', array_values($result['objectclass']), true) === true && in_array('group', array_values($result['objectcategory']),true) === true) {
                    **Group code not yet written**
                }
            }
        }
    }

**Comment by schrotn** [comment]
Fair warning: I'm far from a PHP programmer.  I know enough to screw around with it.  Please do your due diligence first before trying this script I've attached.

Here's a hacked up version of the LDAP sync script that will pull the 'Managed By' attribute from the groups and set it as an alias for the user designated.
It does not distinguish from security and distribution groups yet, even though the options are at the top.  Wishful thinking on my part.  But I'm working on it.

Also, it will not remove aliases from users if they are removed from the 'Managed By' attribute yet.  This is an add only script right now.  Eventually I'd like to get it reading the members of the groups and have it add/modify/delete aliases as the group changes.  But small steps first...

[MailWatch-AD-Sync-schrotn-edit.txt](https://github.com/E-F-A/v3/files/1353845/MailWatch-AD-Sync-schrotn-edit.txt)

**Comment by schrotn** [comment]
I've managed to get create and modify working for groups.  As usual, this is done by a mediocre programmer so vet the code before you use it.  Groups as of this release are create & modify.  Users are still create only.
[MailWatch-AD-Sync-schrotn-edit2.txt](https://github.com/E-F-A/v3/files/1357810/MailWatch-AD-Sync-schrotn-edit2.txt)

To move further, I would like to propose a change to either the mailscanner or EFA database.  If the powers that be like my chnages, I'd like to propose adding an optional GUID entry to the database so there is a concrete reference point for LDAP/AD syncing.  Whether it is an entry in the user_filter & users table in mailscanner, or a separate table in the EFA database makes no difference to me.

**Comment by schrotn** [comment]
Apologies for bringing this up again, but I'd like to know how I need to proceed.
Will I need to do my own custom database or is this something EFA would consider incorporating into one of the existing databases?

**Comment by shawniverson** [comment]
Moving to v4 closing v3 development
