### ISSUE TITLE
Include hostname in upgrade email notices 

### ISSUE THREAD

**Issue by TheGr8Wonder** [E-F-A/v3#397]
https://forum.efa-project.org/viewtopic.php?f=13&p=10741#p10741

**Comment by TheGr8Wonder** [comment]
Emails will now include the hostname in subject and body for...

-Update Failed
-Low disk space
-Pending kernel update
-Update Complete

**Comment by shawniverson** [comment]
Added in commit e46a534f9da0407e814becaf104e6a6c92100a35
