### ISSUE TITLE
/usr/bin/clamav-unofficial-sigs.sh  config version not updated to  required version 72

### ISSUE THREAD

**Issue by jakes670** [E-F-A/v3#402]
HI Everyone

I noticed some some Phishing emails came in to my EFA-3.0.2.5  server

I did a test thru Hetzner and their servers is picking up the message as (Sanesecurity.Phishing.Fake.26925)

I noticed the update for /usr/bin/clamav-unofficial-sigs.sh gives a error 
ERROR: Your config version 69 is not compatible with the min required version 72

I tested 2 different servers both is affected 

Below is some test I ran, any advice how to fix the config file for clamav-unofficial-sigs.sh

root@smtp7 admin]# /usr/bin/clamav-unofficial-sigs.sh
################################################################################
 eXtremeSHOK.com ClamAV Unofficial Signature Updater
 Version: v5.6.2 (2017-03-19)
 Required Configuration Version: v72
 Copyright (c) Adrian Jon Kriel :: admin@extremeshok.com
################################################################################
=======================================================
Loading config: /etc/clamav-unofficial-sigs/master.conf
=======================================================
===================================================
Loading config: /etc/clamav-unofficial-sigs/os.conf
===================================================
=====================================================
Loading config: /etc/clamav-unofficial-sigs/user.conf
=====================================================
================================================================================
ERROR: Your config version 69 is not compatible with the min required version 72
================================================================================

[root@smtp7 cron.d]# dig rsync.sanesecurity.net +noedns

; <<>> DiG 9.8.2rc1-RedHat-9.8.2-0.62.rc1.el6_9.4 <<>> rsync.sanesecurity.net +noedns
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 8738
;; flags: qr rd ra; QUERY: 1, ANSWER: 25, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;rsync.sanesecurity.net.                IN      A

;; ANSWER SECTION:
rsync.sanesecurity.net. 801     IN      A       208.79.241.67
rsync.sanesecurity.net. 801     IN      A       94.142.245.58
rsync.sanesecurity.net. 801     IN      A       45.55.230.41
rsync.sanesecurity.net. 801     IN      A       188.226.251.154
rsync.sanesecurity.net. 801     IN      A       213.152.3.110
rsync.sanesecurity.net. 801     IN      A       46.21.115.195
rsync.sanesecurity.net. 801     IN      A       128.232.98.11
rsync.sanesecurity.net. 801     IN      A       212.24.139.164
rsync.sanesecurity.net. 801     IN      A       37.59.95.34
rsync.sanesecurity.net. 801     IN      A       185.66.251.102
rsync.sanesecurity.net. 801     IN      A       217.70.178.190
rsync.sanesecurity.net. 801     IN      A       185.87.185.65
rsync.sanesecurity.net. 801     IN      A       185.103.157.37
rsync.sanesecurity.net. 801     IN      A       67.225.188.197
rsync.sanesecurity.net. 801     IN      A       147.102.222.211
rsync.sanesecurity.net. 801     IN      A       141.42.206.35
rsync.sanesecurity.net. 801     IN      A       95.154.208.105
rsync.sanesecurity.net. 801     IN      A       150.214.142.197
rsync.sanesecurity.net. 801     IN      A       212.183.175.206
rsync.sanesecurity.net. 801     IN      A       185.95.29.15
rsync.sanesecurity.net. 801     IN      A       185.12.6.218
rsync.sanesecurity.net. 801     IN      A       194.77.111.24
rsync.sanesecurity.net. 801     IN      A       89.145.113.192
rsync.sanesecurity.net. 801     IN      A       185.85.248.30
rsync.sanesecurity.net. 801     IN      A       176.9.102.216

;; Query time: 0 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Fri Nov 10 16:29:17 2017
;; MSG SIZE  rcvd: 440

[root@smtp7 cron.d]# rsync rsync://rsync.sanesecurity.net/sanesecurity

drwxr-xr-x       12288 2017/11/10 15:52:57 .
-rw-r--r--        1559 2017/11/10 15:47:58 MiscreantPunch-Info.txt
-rw-r--r--        6155 2017/11/10 15:47:58 MiscreantPunch099-INFO-Low.ldb
-rw-r--r--          65 2017/11/10 15:47:58 MiscreantPunch099-INFO-Low.ldb.md5
-rw-r--r--         104 2017/11/10 15:47:58 MiscreantPunch099-INFO-Low.ldb.sha256
-rw-r--r--          72 2017/11/10 15:47:58 MiscreantPunch099-INFO-Low.ldb.sig
-rw-r--r--      447743 2017/11/10 15:47:58 MiscreantPunch099-Low.ldb
-rw-r--r--          60 2017/11/10 15:47:58 MiscreantPunch099-Low.ldb.md5
-rw-r--r--          99 2017/11/10 15:47:58 MiscreantPunch099-Low.ldb.sha256
-rw-r--r--          72 2017/11/10 15:47:58 MiscreantPunch099-Low.ldb.sig
-rw-r--r--        1802 2016/02/18 18:15:39 Sanesecurity_BlackEnergy.yara
-rw-r--r--          65 2016/02/18 18:15:39 Sanesecurity_BlackEnergy.yara.md5
-rw-r--r--         104 2016/02/18 18:15:39 Sanesecurity_BlackEnergy.yara.sha256
-rw-r--r--          72 2016/02/18 18:15:39 Sanesecurity_BlackEnergy.yara.sig
-rw-r--r--        1462 2015/07/01 14:54:14 Sanesecurity_sigtest.yara
-rw-r--r--          61 2015/07/01 14:54:15 Sanesecurity_sigtest.yara.md5
-rw-r--r--         100 2015/07/01 14:54:15 Sanesecurity_sigtest.yara.sha256
-rw-r--r--          72 2015/07/01 14:54:15 Sanesecurity_sigtest.yara.sig
-rw-r--r--        1233 2016/02/22 14:21:33 Sanesecurity_spam.yara
-rw-r--r--          58 2016/02/22 14:54:49 Sanesecurity_spam.yara.md5
-rw-r--r--          97 2016/02/22 14:54:49 Sanesecurity_spam.yara.sha256
-rw-r--r--          72 2016/02/22 14:54:49 Sanesecurity_spam.yara.sig
-rw-r--r--          52 2017/11/10 15:52:57 TIMESTAMP
-rw-r--r--          72 2017/11/10 15:52:57 TIMESTAMP.sig
-rw-r--r--       74456 2017/11/01 15:56:09 badmacro.ndb
-rw-r--r--          48 2017/11/01 15:56:10 badmacro.ndb.md5
-rw-r--r--          87 2017/11/01 15:56:10 badmacro.ndb.sha256
-rw-r--r--          72 2017/11/01 15:56:09 badmacro.ndb.sig
-rw-r--r--      136728 2017/11/10 15:52:29 blurl.ndb
-rw-r--r--          45 2017/11/10 15:52:30 blurl.ndb.md5
-rw-r--r--          84 2017/11/10 15:52:30 blurl.ndb.sha256
-rw-r--r--          72 2017/11/10 15:52:29 blurl.ndb.sig
-rw-r--r--         998 2017/11/10 15:47:04 bofhland_cracked_URL.ndb
-rw-r--r--          60 2017/11/09 18:52:13 bofhland_cracked_URL.ndb.md5
-rw-r--r--          99 2017/11/09 18:52:13 bofhland_cracked_URL.ndb.sha256
-rw-r--r--          72 2017/11/09 18:52:13 bofhland_cracked_URL.ndb.sig
-rw-r--r--        4512 2017/11/10 15:47:04 bofhland_malware_URL.ndb
-rw-r--r--          60 2017/11/09 16:54:40 bofhland_malware_URL.ndb.md5
-rw-r--r--          99 2017/11/09 16:54:40 bofhland_malware_URL.ndb.sha256
-rw-r--r--          72 2017/11/09 16:54:40 bofhland_malware_URL.ndb.sig
-rw-r--r--      106188 2017/11/10 15:47:04 bofhland_malware_attach.hdb
-rw-r--r--          63 2017/10/26 13:00:58 bofhland_malware_attach.hdb.md5
-rw-r--r--         102 2017/10/26 13:00:57 bofhland_malware_attach.hdb.sha256
-rw-r--r--          72 2017/10/26 13:00:57 bofhland_malware_attach.hdb.sig
-rw-r--r--        5484 2017/11/10 15:47:04 bofhland_phishing_URL.ndb
-rw-r--r--          61 2017/11/10 12:52:31 bofhland_phishing_URL.ndb.md5
-rw-r--r--         100 2017/11/10 12:52:31 bofhland_phishing_URL.ndb.sha256
-rw-r--r--          71 2017/11/10 12:52:31 bofhland_phishing_URL.ndb.sig
-rw-r--r--          82 2016/07/13 21:44:08 crdfam.clamav.hdb
-rw-r--r--          53 2016/07/13 21:53:57 crdfam.clamav.hdb.md5
-rw-r--r--          92 2016/07/13 21:53:57 crdfam.clamav.hdb.sha256
-rw-r--r--          72 2016/07/13 21:53:56 crdfam.clamav.hdb.sig
-rw-r--r--         309 2012/04/17 22:45:02 doppelstern-phishtank.ndb
-rw-r--r--          61 2013/03/28 15:50:15 doppelstern-phishtank.ndb.md5
-rw-r--r--         100 2013/03/28 15:50:15 doppelstern-phishtank.ndb.sha256
-rw-r--r--          72 2013/03/28 15:50:15 doppelstern-phishtank.ndb.sig
-rw-r--r--          65 2013/07/26 10:45:07 doppelstern.hdb
-rw-r--r--          51 2013/07/25 19:49:21 doppelstern.hdb.md5
-rw-r--r--          90 2013/07/25 19:49:21 doppelstern.hdb.sha256
-rw-r--r--          72 2013/07/25 19:49:21 doppelstern.hdb.sig
-rw-r--r--         185 2013/07/26 10:45:07 doppelstern.ndb
-rw-r--r--          51 2013/07/25 19:49:21 doppelstern.ndb.md5
-rw-r--r--          90 2013/07/25 19:49:21 doppelstern.ndb.sha256
-rw-r--r--          72 2013/07/25 19:49:21 doppelstern.ndb.sig
-rw-r--r--        9294 2017/02/13 18:34:34 foxhole_all.cdb
-rw-r--r--          51 2017/02/13 18:34:34 foxhole_all.cdb.md5
-rw-r--r--          90 2017/02/13 18:34:34 foxhole_all.cdb.sha256
-rw-r--r--          72 2017/02/13 18:34:34 foxhole_all.cdb.sig
-rw-r--r--        5794 2016/11/21 10:55:46 foxhole_all.ndb
-rw-r--r--          51 2016/11/21 10:55:47 foxhole_all.ndb.md5
-rw-r--r--          90 2016/11/21 10:55:47 foxhole_all.ndb.sha256
-rw-r--r--          72 2016/11/21 10:55:47 foxhole_all.ndb.sig
-rw-r--r--      103813 2017/11/07 17:54:38 foxhole_filename.cdb
-rw-r--r--          56 2017/11/07 17:54:38 foxhole_filename.cdb.md5
-rw-r--r--          95 2017/11/07 17:54:38 foxhole_filename.cdb.sha256
-rw-r--r--          72 2017/11/07 17:54:38 foxhole_filename.cdb.sig
-rw-r--r--       46327 2017/11/01 11:56:01 foxhole_generic.cdb
-rw-r--r--          55 2017/11/01 11:56:02 foxhole_generic.cdb.md5
-rw-r--r--          94 2017/11/01 11:56:02 foxhole_generic.cdb.sha256
-rw-r--r--          72 2017/11/01 11:56:02 foxhole_generic.cdb.sig
-rw-r--r--        3888 2017/08/18 19:56:29 foxhole_js.cdb
-rw-r--r--          50 2017/08/18 19:56:30 foxhole_js.cdb.md5
-rw-r--r--          89 2017/08/18 19:56:29 foxhole_js.cdb.sha256
-rw-r--r--          72 2017/08/18 19:56:29 foxhole_js.cdb.sig
-rw-r--r--         230 2016/11/21 10:55:51 foxhole_js.ndb
-rw-r--r--          50 2016/11/21 10:55:52 foxhole_js.ndb.md5
-rw-r--r--          89 2016/11/21 10:55:51 foxhole_js.ndb.sha256
-rw-r--r--          72 2016/11/21 10:55:51 foxhole_js.ndb.sig
-rw-r--r--        1147 2017/09/13 10:51:05 foxhole_mail.cdb
-rw-r--r--          52 2017/09/13 10:54:36 foxhole_mail.cdb.md5
-rw-r--r--          91 2017/09/13 10:54:36 foxhole_mail.cdb.sha256
-rw-r--r--          72 2017/09/13 10:54:36 foxhole_mail.cdb.sig
-rw-r--r--          45 2015/12/15 15:48:02 grab_winnow.err
-rw-r--r--       48176 2015/08/05 09:24:44 hackingteam.hsb
-rw-r--r--          51 2015/08/07 09:53:07 hackingteam.hsb.md5
-rw-r--r--          90 2015/08/07 09:53:07 hackingteam.hsb.sha256
-rw-r--r--          72 2015/08/07 09:53:07 hackingteam.hsb.sig
-rw-r--r--     7105375 2017/11/10 10:55:27 junk.ndb
-rw-r--r--          44 2017/11/10 10:55:27 junk.ndb.md5
-rw-r--r--          83 2017/11/10 10:55:27 junk.ndb.sha256
-rw-r--r--          72 2017/11/10 10:55:27 junk.ndb.sig
-rw-r--r--      143996 2017/11/10 15:52:28 jurlbl.ndb
-rw-r--r--          46 2017/11/10 15:52:29 jurlbl.ndb.md5
-rw-r--r--          85 2017/11/10 15:52:28 jurlbl.ndb.sha256
-rw-r--r--          72 2017/11/10 15:52:28 jurlbl.ndb.sig
-rw-r--r--      232458 2017/11/10 15:52:29 jurlbla.ndb
-rw-r--r--          47 2017/11/10 15:52:29 jurlbla.ndb.md5
-rw-r--r--          86 2017/11/10 15:52:29 jurlbla.ndb.sha256
-rw-r--r--          72 2017/11/10 15:52:29 jurlbla.ndb.sig
-rw-r--r--      244847 2017/08/04 16:53:30 lott.ndb
-rw-r--r--          44 2017/08/04 16:53:30 lott.ndb.md5
-rw-r--r--          83 2017/08/04 16:53:30 lott.ndb.sha256
-rw-r--r--          72 2017/08/04 16:53:30 lott.ndb.sig
-rw-r--r--        2036 2017/11/10 15:48:01 malware.expert.fp
-rw-r--r--          52 2017/11/10 15:48:01 malware.expert.fp.md5
-rw-r--r--          91 2017/11/10 15:48:01 malware.expert.fp.sha256
-rw-r--r--          72 2017/11/10 15:48:01 malware.expert.fp.sig
-rw-r--r--       24489 2017/11/10 15:48:01 malware.expert.hdb
-rw-r--r--          53 2017/11/10 15:48:01 malware.expert.hdb.md5
-rw-r--r--          92 2017/11/10 15:48:01 malware.expert.hdb.sha256
-rw-r--r--          72 2017/11/10 15:48:01 malware.expert.hdb.sig
-rw-r--r--       21006 2017/11/10 15:48:01 malware.expert.ldb
-rw-r--r--          53 2017/11/10 15:48:01 malware.expert.ldb.md5
-rw-r--r--          92 2017/11/10 15:48:01 malware.expert.ldb.sha256
-rw-r--r--          72 2017/11/10 15:48:01 malware.expert.ldb.sig
-rw-r--r--       89907 2017/11/10 15:48:01 malware.expert.ndb
-rw-r--r--          53 2017/11/10 15:48:01 malware.expert.ndb.md5
-rw-r--r--          92 2017/11/10 15:48:01 malware.expert.ndb.sha256
-rw-r--r--          72 2017/11/10 15:48:01 malware.expert.ndb.sig
-rw-r--r--       73808 2017/06/29 08:54:44 malwarehash.hsb
-rw-r--r--          51 2017/06/29 08:55:32 malwarehash.hsb.md5
-rw-r--r--          90 2017/06/29 08:55:32 malwarehash.hsb.sha256
-rw-r--r--          72 2017/06/29 08:55:32 malwarehash.hsb.sig
-rw-r--r--     4015520 2017/11/07 18:51:48 phish.ndb
-rw-r--r--          45 2017/11/07 18:51:49 phish.ndb.md5
-rw-r--r--          84 2017/11/07 18:51:49 phish.ndb.sha256
-rw-r--r--          72 2017/11/07 18:51:48 phish.ndb.sig
-rw-r--r--     3092920 2017/11/10 15:46:13 phishtank.ndb
-rw-r--r--          49 2017/11/10 13:52:46 phishtank.ndb.md5
-rw-r--r--          88 2017/11/10 13:52:46 phishtank.ndb.sha256
-rw-r--r--          72 2017/11/10 13:52:46 phishtank.ndb.sig
-rw-r--r--       41659 2017/11/10 15:46:13 porcupine.hsb
-rw-r--r--          49 2017/11/10 14:53:11 porcupine.hsb.md5
-rw-r--r--          88 2017/11/10 14:53:11 porcupine.hsb.sha256
-rw-r--r--          72 2017/11/10 14:53:11 porcupine.hsb.sig
-rw-r--r--      200889 2017/11/10 15:46:11 porcupine.ndb
-rw-r--r--          49 2017/11/10 08:54:20 porcupine.ndb.md5
-rw-r--r--          88 2017/11/10 08:54:20 porcupine.ndb.sha256
-rw-r--r--          72 2017/11/10 08:54:20 porcupine.ndb.sig
-rw-r--r--       11122 2015/09/15 12:21:01 readme.txt
-rw-r--r--       46807 2017/11/10 08:54:14 rogue.hdb
-rw-r--r--          45 2017/11/10 08:54:14 rogue.hdb.md5
-rw-r--r--          84 2017/11/10 08:54:14 rogue.hdb.sha256
-rw-r--r--          71 2017/11/10 08:54:14 rogue.hdb.sig
-rw-r--r--       11098 2016/10/18 15:56:19 sanesecurity.ftm
-rw-r--r--          52 2016/10/18 15:56:19 sanesecurity.ftm.md5
-rw-r--r--          91 2016/10/18 15:56:19 sanesecurity.ftm.sha256
-rw-r--r--          72 2016/10/18 15:56:19 sanesecurity.ftm.sig
-rw-r--r--     1893951 2017/10/26 11:56:22 scam.ndb
-rw-r--r--          44 2017/10/26 11:56:23 scam.ndb.md5
-rw-r--r--          83 2017/10/26 11:56:23 scam.ndb.sha256
-rw-r--r--          72 2017/10/26 11:56:23 scam.ndb.sig
-rw-r--r--    14174858 2017/11/10 15:45:20 scamnailer.ndb
-rw-r--r--          50 2017/08/03 17:55:26 scamnailer.ndb.md5
-rw-r--r--          89 2017/08/03 17:55:26 scamnailer.ndb.sha256
-rw-r--r--          72 2017/08/03 17:55:26 scamnailer.ndb.sig
-rw-r--r--        2174 2017/05/03 10:56:36 shelter.ldb
-rw-r--r--          47 2017/05/03 10:56:37 shelter.ldb.md5
-rw-r--r--          86 2017/05/03 10:56:36 shelter.ldb.sha256
-rw-r--r--          72 2017/05/03 10:56:36 shelter.ldb.sig
-rw-r--r--          76 2017/11/10 15:52:33 sigs_updated.txt
-rw-r--r--        7537 2017/10/25 09:01:59 sigwhitelist.ign2
-rw-r--r--          53 2017/10/25 09:02:00 sigwhitelist.ign2.md5
-rw-r--r--          92 2017/10/25 09:02:00 sigwhitelist.ign2.sha256
-rw-r--r--          72 2017/10/25 09:02:00 sigwhitelist.ign2.sig
-rw-r--r--         556 2017/05/05 11:56:56 spam.ldb
-rw-r--r--          44 2017/05/05 11:56:57 spam.ldb.md5
-rw-r--r--          83 2017/05/05 11:56:57 spam.ldb.sha256
-rw-r--r--          72 2017/05/05 11:56:56 spam.ldb.sig
-rw-r--r--        1391 2017/04/28 09:56:28 spamattach.hdb
-rw-r--r--          50 2017/04/28 09:56:28 spamattach.hdb.md5
-rw-r--r--          89 2017/04/28 09:56:28 spamattach.hdb.sha256
-rw-r--r--          72 2017/04/28 09:56:28 spamattach.hdb.sig
-rw-r--r--       13736 2017/10/18 16:00:16 spamimg.hdb
-rw-r--r--          47 2017/10/18 16:00:16 spamimg.hdb.md5
-rw-r--r--          86 2017/10/18 16:00:16 spamimg.hdb.sha256
-rw-r--r--          72 2017/10/18 16:00:16 spamimg.hdb.sig
-rw-r--r--     2035661 2017/11/08 00:48:07 spear.ndb
-rw-r--r--          45 2017/11/08 00:52:19 spear.ndb.md5
-rw-r--r--          84 2017/11/08 00:52:19 spear.ndb.sha256
-rw-r--r--          72 2017/11/08 00:52:18 spear.ndb.sig
-rw-r--r--       83120 2017/11/08 00:52:19 spearl.ndb
-rw-r--r--          46 2017/11/08 00:52:19 spearl.ndb.md5
-rw-r--r--          85 2017/11/08 00:52:19 spearl.ndb.sha256
-rw-r--r--          72 2017/11/08 00:52:19 spearl.ndb.sig
-rw-r--r--      526635 2017/11/10 15:45:25 winnow.attachments.hdb
-rw-r--r--          57 2017/11/10 15:45:25 winnow.attachments.hdb.md5
-rw-r--r--          96 2017/11/10 15:45:25 winnow.attachments.hdb.sha256
-rw-r--r--          72 2017/11/10 15:45:25 winnow.attachments.hdb.sig
-rw-r--r--         660 2017/11/10 15:45:25 winnow.complex.patterns.ldb
-rw-r--r--          62 2017/11/10 15:45:25 winnow.complex.patterns.ldb.md5
-rw-r--r--         101 2017/11/10 15:45:25 winnow.complex.patterns.ldb.sha256
-rw-r--r--          72 2017/11/10 15:45:25 winnow.complex.patterns.ldb.sig
-rw-r--r--          66 2017/11/10 15:45:25 winnow_bad_cw.hdb
-rw-r--r--          52 2017/11/10 15:45:25 winnow_bad_cw.hdb.md5
-rw-r--r--          91 2017/11/10 15:45:25 winnow_bad_cw.hdb.sha256
-rw-r--r--          72 2017/11/10 15:45:25 winnow_bad_cw.hdb.sig
-rw-r--r--       25990 2017/11/10 15:45:25 winnow_extended_malware.hdb
-rw-r--r--          62 2017/11/10 15:45:25 winnow_extended_malware.hdb.md5
-rw-r--r--         101 2017/11/10 15:45:25 winnow_extended_malware.hdb.sha256
-rw-r--r--          72 2017/11/10 15:45:25 winnow_extended_malware.hdb.sig
-rw-r--r--         159 2017/11/10 15:45:25 winnow_extended_malware_links.ndb
-rw-r--r--          68 2017/11/10 15:45:25 winnow_extended_malware_links.ndb.md5
-rw-r--r--         107 2017/11/10 15:45:25 winnow_extended_malware_links.ndb.sha256
-rw-r--r--          72 2017/11/10 15:45:25 winnow_extended_malware_links.ndb.sig
-rw-r--r--       53122 2017/11/10 15:45:25 winnow_malware.hdb
-rw-r--r--          53 2017/11/10 15:45:25 winnow_malware.hdb.md5
-rw-r--r--          92 2017/11/10 15:45:25 winnow_malware.hdb.sha256
-rw-r--r--          72 2017/11/10 15:45:25 winnow_malware.hdb.sig
-rw-r--r--        3782 2017/11/10 15:45:25 winnow_malware.yara
-rw-r--r--          54 2017/11/10 15:45:25 winnow_malware.yara.md5
-rw-r--r--          93 2017/11/10 15:45:25 winnow_malware.yara.sha256
-rw-r--r--          72 2017/11/10 15:45:25 winnow_malware.yara.sig
-rw-r--r--      970866 2017/11/10 15:45:26 winnow_malware_links.ndb
-rw-r--r--          60 2017/11/10 15:52:31 winnow_malware_links.ndb.md5
-rw-r--r--          99 2017/11/10 15:52:31 winnow_malware_links.ndb.sha256
-rw-r--r--          72 2017/11/10 15:52:31 winnow_malware_links.ndb.sig
-rw-r--r--      377547 2017/11/10 15:45:26 winnow_phish_complete.ndb
-rw-r--r--          61 2017/11/10 15:52:32 winnow_phish_complete.ndb.md5
-rw-r--r--         100 2017/11/10 15:52:32 winnow_phish_complete.ndb.sha256
-rw-r--r--          72 2017/11/10 15:52:31 winnow_phish_complete.ndb.sig
-rw-r--r--      377547 2017/11/10 15:45:26 winnow_phish_complete_url.ndb
-rw-r--r--          65 2017/11/10 15:52:32 winnow_phish_complete_url.ndb.md5
-rw-r--r--         104 2017/11/10 15:52:32 winnow_phish_complete_url.ndb.sha256
-rw-r--r--          72 2017/11/10 15:52:32 winnow_phish_complete_url.ndb.sig
-rw-r--r--      189684 2017/11/10 15:45:26 winnow_spam_complete.ndb
-rw-r--r--          60 2017/11/10 15:52:32 winnow_spam_complete.ndb.md5
-rw-r--r--          99 2017/11/10 15:52:32 winnow_spam_complete.ndb.sha256
-rw-r--r--          72 2017/11/10 15:52:32 winnow_spam_complete.ndb.sig

Many Thanks
Jaco

**Comment by shawniverson** [comment]
Confirmed issue.

**Comment by shawniverson** [comment]
Replace master.conf in /etc/clamav-unofficial-sigs/master.conf with /etc/clamav-unofficial-sigs/master.conf.rpmnew

Move any custom settings from your old master.conf to the new one.

**Comment by shawniverson** [comment]
Leaving alone, must be fixed manually updating from <3.0.2.5.  Significant changes in master.conf.  Will provide a release note.  Future updates will track changes to conf files and update accordingly.

**Comment by shawniverson** [comment]
Issue identified in RELEASENOTES with steps to fix  in commit c7ab369ba8d2a3ced87c3aa6e5b2a672ed302dcd
