### ISSUE TITLE
Plus addressing support

### ISSUE THREAD

**Issue by sriccio** [E-F-A/v3#413]
Hi,

I would like to suggest to support Plus addressing in EFA's MailWatch interface.

It is possible to allow mails to be sent, for example, to:

`user@domain.tld` or `user+facebook@domain.tld` or `user+misc@domain.tld`

In postfix this is acheived by adding In main.cf

```
recipient_delimiter = +
```

This works well, the mails are routed correctly to the final MTA and there is moved in the right folder.

However, if I log in to the MailWatch interface with the user `user@domain.tld`, it wont be listed.

This is because the to_address stored in the maillog db is `user+facebook@domain.tld`.

Maybe a workaround would be that MailWatch query into the db looks for to_address matching `user@domain.tld` AND `user+*@domain.tld` ?

Just an idea :)

Cheers,
Sébastien

**Comment by shawniverson** [comment]
@sriccio Let me reach out to MailWatch team and see what needs done here.

**Comment by sriccio** [comment]
@shawniverson Thank you for your reply.

In the meantime, I modded `address_sql_filter` function in `functions.php` to look like this:

```
        case 'U': // User - show only specific addresses
            foreach ($addresses as $address) {
                $ar = explode('@', $address);
                $username = $ar[0];
                $domainname = $ar[1];
                if (defined('FILTER_TO_ONLY') && FILTER_TO_ONLY) {
                    $sqladdr_arr[] = "to_address like '$address%' OR to_address like '$username+%@$domainname'";
                } else {
                    $sqladdr_arr[] = "to_address like '$address%' OR to_address like '$username+%@$domainname' OR from_address = '$address' OR from_address like '$username+%@$domainname'";
                }
            }
            $sqladdr = implode(' OR ', $sqladdr_arr);
            break;
```

It seems to work as expected, but I don't know if there are other places where it should be adapted too.
Would love to hear what MailWatch team thinks about it :)

Thanks again.
