### ISSUE TITLE
Add remote database support

### ISSUE THREAD

**Issue by ghost** [E-F-A/v3#415]
I will try to make patches for remote database support.
This will allow for high availability using a remote SQL cluster like galera.

**Comment by bilias** [comment]
Can I have some feedback if this will be accepted?

If yes then we have to see about update script and if there will be a transition option script to change values in other places that don't read from EFA-Config.

Also there are various places that scripts are run with MYSQL_ROOT.
This might not be an option on a remote DB.

**Comment by shawniverson** [comment]
What?  There's no PR.

**Comment by shawniverson** [comment]
Not v3, but v4 is possible.

**Comment by bilias** [comment]
ok, i'll make patches for V4
I believe it's easier there since it will be clean

Do you have an expected date of first release?

**Comment by shawniverson** [comment]
@bilias I think I am going to do a release once https://github.com/E-F-A/v4/projects/2 is complete.  It will be pretty basic, but have all eFa v3 functionality.  That way folks can get on CentOS 7 while I work on a GUI configuration interface and more features.
